import "./globals.css";
import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-jakarta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    fetch: (input: RequestInfo | URL, init?: RequestInit | undefined) =>
      fetch(input, {
        ...init,
        cache: process.env.NODE_ENV === "development" ? "no-cache" : undefined,
      }),
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoryblokProvider>
      <html
        lang="en"
        className={`${inter.variable} ${plus_jakarta_sans.variable}`}
      >
        <body className="font-sans">
          <header className="bg-blue-50">
            <nav className="layout py-8 flex justify-between items-baseline">
              <Link href={"/"}>Home</Link>
              <Link href={"/tours"}>Browse Tours</Link>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
